### PR TITLE
Fix klarna custom shipping method description getter

### PR DESCRIPTION
**Pull request by pawelphilipczyk**
As described in #700 currently Klarna payment fails for custom shipping methods.

I can update this PR if decision is made to use `name` or `localizedDescription` for standard shipping methods instead of deprecated `description`. See docs related to this: https://docs.commercetools.com/api/projects/shippingMethods#shippingmethod

### CODE REVIEW

**Comment by lojzatran** [comment]
Thanks for the PR! Your suggestion sounds good. I have a suggestion for you, WDYT?

First check for `localizedDescription` field - choose the correct locale using the locale from klarna method (https://github.com/commercetools/commercetools-adyen-integration/blob/master/extension/src/paymentHandler/klarna-make-payment.handler.js#L68). If this field doesn’t exist, then fall back to `description`. And if that doesn’t `description`, then fall back to `name` (this part is already done).

In case of custom method use `shippingMethodName` as you suggested.

**Comment by pawelphilipczyk** [comment]
@lojzatran I've updated it but I'm not sure it's what you meant. The level of "fallbacking" here gets complicated ;) I'm trying to use `_localizeOrFallback` here with fallback to deprecated `description`. 

It will return some falsy value if both are empty so I've added additional fallback with `KLARNA_DEFAULT_SHIPPING_METHOD_DESCRIPTION` outside of that function. 

That will also handle the case if we have custom shipping method and shippingMethodName is not available for some reason? I'm not sure if that can ever happen because that property is required in `setCustomShippingMethod` action but maybe it can be empty string. 

I haven't tested it yet. Do you have some tests for it or quick way to test "manually"? I will do some testing next week but we don't have all those cases.

**Comment by lojzatran** [comment]
@pawelphilipczyk sorry for the late reply. We don't have a quick way to manually test it, but we have automated tests. Unfortunately they are not triggered for the forks. It would be good if you can also add unit/integration tests for this change. If it's too much, I can also take over the PR and try finish it.

**Comment by pawelphilipczyk** [comment]
@lojzatran I can give it a try. 

Just to point me in the right direction, I'm assuming this is where it should be added: `commercetools-adyen-integration/extension/test/unit/klarna-make-payment.handler.spec.js`?

**Comment by lojzatran** [comment]
> @lojzatran I can give it a try.
> 
> Just to point me in the right direction, I'm assuming this is where it should be added: `commercetools-adyen-integration/extension/test/unit/klarna-make-payment.handler.spec.js`?

Yes, I would try to add it there like a new unit test.

**Comment by lojzatran** [comment]
Hi @pawelphilipczyk 
Do you have any news here? If not, I will start working on it and try to finish it within this week.
Thank you.

**Comment by pawelphilipczyk** [comment]
Unfortunately I have had to switch to other more important tasks before I get back to this (which will be not until few weeks from now on). 
I'll be happy to test whatever fix you provide.

**Pull request merged**
