### PR TITLE
add extension function for azure

### PR DESCRIPTION
**Pull request by moritz-deissner-turbinekreuzberg**
This extension function is working for us on MS Azure. 

Addresses: #825

### CODE REVIEW

**Comment by ahmetoz** [comment]
@moritz-deissner-turbinekreuzberg thank you very much for the contribution, we will check review asap. 🙏🏽

**Comment by ijn-kruso** [comment]
@moritz-deissner-turbinekreuzberg What's the status on this PR? We have a client that could use the feature soon.

**Comment by moritz-deissner-turbinekreuzberg** [comment]
> @moritz-deissner-turbinekreuzberg What's the status on this PR? We have a client that could use the feature soon.

Beats me. The is no change since December 16 2021 when @ahmetoz said they would do a review.

**Comment by ahmetoz** [comment]
Sorry for the late reply @moritz-deissner-turbinekreuzberg,

We've added it to our backlog, checked this PR and opened an internal investigation, the delay here related to that our experience of Azure setup so we could not test it out easily and now it's waiting our tech time investigation first on an Azure Function setup.

I would have some comments for the PR for the major missing points to make it as part of the other deployment examples such as GCP functions or AWS Lambda:

- PR covers only the extension, so current change does not cover the notification deployment.
- PR does not cover test cases to ensure it's working with normal path or other edge cases.
- PR does not have a documentation to describe how it could be deployed to Azure functions.

If you want to consider contribution for this based on the points above, we would like to help on the detail pull request reviews.

**Comment by praveenkumarct** [comment]
Closing this PR. https://github.com/commercetools/commercetools-adyen-integration/pull/993
I have created PR with more detailed documentation and scripts for both extension and notification.
We will release it soon.

**Comment by praveenkumarct** [comment]
https://github.com/commercetools/commercetools-adyen-integration/releases/tag/v9.9.2
Released.

**Pull request closed without merging**
