### PR TITLE
Adyen PayByLink

### LINKED ISSUE #717: Support for PayByLink
Let's add the support for Pay By Link: https://docs.adyen.com/online-payments/pay-by-link/api

### PR DESCRIPTION
**Pull request by Fifciu**
Support for Adyen's PayByLink
closes #717

### CODE REVIEW

**Comment by Fifciu** [comment]
@butenkor could you please take a look at this?

**Comment by butenkor** [comment]
Hi @Fifciu, thanks for the PR. We are checking your approach with Adyen and will let you know once we checked the eventual obstacles.

**Comment by Fifciu** [comment]
Any news @butenkor?

**Comment by lojzatran** [comment]
> Any news @butenkor?

Hi @Fifciu, we are still discussing this PR with Adyen and internally. It might take a while since your approach is different from what we currently support (web components). We will let you know once we reach the conclusion. Thank you for your patience.

**Comment by Fifciu** [comment]
I am looking forward to some feedback as this feature provides support for every payment method with only configuring it in Adyen's dashboard (no need to modify the frontend code!) so it's especially demanded.

**Pull request closed without merging**
