### PR TITLE
Fix potential error with merchantReference validation

### PR DESCRIPTION
**Pull request by zackpollard**
Do more checks to ensure the underlying objects exist before checking that the merchantReference field isn't empty

### CODE REVIEW

**Comment by LEQADA** [comment]
Thank you for the PR @zackpollard . A unit test to reproduce the failing case would be perfect

**Comment by zackpollard** [comment]
> Thank you for the PR @zackpollard . A unit test to reproduce the failing case would be perfect

Agreed, this logic is applied to a lot of different validations in that file however, should I create a unit test for each one to ensure this doesn't happen for any of those in the future too?

**Comment by LEQADA** [comment]
One case should be enough. The logic is the same.

**Comment by zackpollard** [comment]
I've now added a unit test that invokes all those validations with an empty payment object which would have failed before in this case. It's using the same it case but is looping over all of the different validations that could have this potential error case introduced through a degradation

**Comment by zackpollard** [comment]
> Can you run `npm run lint` and check if there are any errors?

Done :)

**Pull request merged**
